### ISSUE TITLE
ManagerClientThread Object Streams could not initialize

### ISSUE THREAD

**Issue by krasi0** [davechurchill/StarcraftAITournamentManager#25]
Any idea what may be causing the following Java exception when running the TM?

        at server.ServerClientThread.setupConnectionStreams(ServerClientThread.java:76)
       at server.ServerClientThread.run(ServerClientThread.java:44)
java.io.StreamCorruptedException: invalid stream header: 0300002F
       at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:857)
       at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
       at server.ServerClientThread.setupConnectionStreams(ServerClientThread.java:71)
       at server.ServerClientThread.run(ServerClientThread.java:44)

**Comment by krasi0** [comment]
It's turned out that some Ukrainian IP was bruteforcing the protocol (and opening occasional connections to the TM server). The Linux firewall (iptables) has solved the issue.

**Comment by davechurchill** [comment]
Thanks for updating! Glad you fixed it

On Feb 26, 2018 3:14 PM, "krasi0" <notifications@github.com> wrote:

It's turned out that some Ukrainian IP was bruteforcing the protocol (and
opening occasional connections to the TM server). The Linux firewall
(iptables) has solved the issue.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davechurchill/StarcraftAITournamentManager/issues/25#issuecomment-368605259>,
or mute the thread
